apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-deployment
  labels:
    app: nodejs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - name: nodejs
        image: node
        command: ["sh"]
        stdin: true
        ports:
          - containerPort: 3000
        volumeMounts:
        - mountPath: /app
          name: app-volume
      volumes:
      - name: app-volume
        hostPath:
          path: /home/sally/Documents/k-project              