- name: Deploy Express.js project on Linux 
  hosts: localhost
  tasks:
    - name: create namespace 
      kubernetes.core.k8s:
        name: testing
        api_version: v1
        kind: Namespace
        state: present
      
    - name: Create Express app deployment
      kubernetes.core.k8s:
        state: present
        namespace: testing
        api_version: v1
        src: ../kubernetes/IAC/nodejs-deployment.yaml

    - name: Create Express app nodeType service
      kubernetes.core.k8s:
        state: present
        namespace: testing
        src: ../kubernetes/IAC/nodejs-service.yaml

    - name: Create Mongodb deployment
      kubernetes.core.k8s:
        state: present
        namespace: testing
        src: ../kubernetes/IAC/mongodb-deployment.yaml

    - name: Create Mongodb clusterIp service
      kubernetes.core.k8s:
        state: present
        namespace: testing
        src: ../kubernetes/IAC/mongodb-service.yaml
